binary_sensor:
  name: simon_home
  platform: 'bayesian'
  prior: 0.5
  probability_threshold: 0.95
  observations:
    - entity_id: device_tracker.eternal_damnation_2
      prob_given_true: 0.8
      prob_given_false: 0.2
      platform: 'state'
      to_state: 'home'
    - entity_id: device_tracker.simon_phone
      prob_given_true: 0.8
      prob_given_false: 0.2
      platform: 'state'
      to_state: 'home'
    - entity_id: device_tracker.simonsapplewatch
      prob_given_true: 0.8
      prob_given_false: 0.2
      platform: 'state'
      to_state: 'home'

