- alias: 'Mark Simon Away'
  condition:
    condition: state
    entity_id: input_boolean.simon_home
    state: 'on'
  trigger:
    - platform: state
      entity_id: device_tracker.eternal_damnation_2, device_tracker.simon_phone
      to: 'not_home'
      for:
        minutes: 10
  action:
    - service: homeassistant.turn_off
      entity_id: input_boolean.simon_home

- alias: 'Mark Simon Home'
  condition:
    condition: state
    entity_id: input_boolean.simon_home
    state: 'off'
  trigger:
    - platform: state
      entity_id: device_tracker.eternal_damnation_2, device_tracker.simon_phone
      to: 'home' 
  action:
    - service: homeassistant.turn_on
      entity_id: input_boolean.simon_home

- alias: 'Mark Nancy Away'
  condition:
    condition: state
    entity_id: input_boolean.nancy_home
    state: 'on'
  trigger:
    - platform: state
      entity_id: device_tracker.eternal_damnation
      to: 'not_home'
      for:
        minutes: 10
  action:
    - service: homeassistant.turn_off
      entity_id: input_boolean.nancy_home

- alias: 'Mark Nancy Home'
  condition:
    condition: state
    entity_id: input_boolean.nancy_home
    state: 'off'
  trigger:
    - platform: state
      entity_id: device_tracker.eternal_damnation
      to: 'home' 
  action:
     service: homeassistant.turn_on
     entity_id: input_boolean.nancy_home

- alias: 'Mark Away'
  condition:
    condition: state
    entity_id: input_boolean.home
    state: 'on'
  trigger:
    - platform: state
      entity_id: input_boolean.simon_home
      to: 'off'
    - platform: state
      entity_id: input_boolean.nancy_home
      to: 'off'
  action:
    - service: homeassistant.turn_ofF
      entity_id: input_boolean.home

- alias: 'Mark Home'
  condition:
    condition: state
    entity_id: input_boolean.home
    state: 'off'
  trigger:
    - platform: state
      entity_id: input_boolean.simon_home
      to: 'on' 
    - platform: state
      entity_id: input_boolean.nancy_home
      to: 'on' 
  action:
     service: homeassistant.turn_on
     entity_id: input_boolean.home

# ==================================================
# Returns
# ==================================================
 
- alias: 'Return evening'
  trigger:
    platform: state
    entity_id: input_boolean.home
    from: 'off'
    to: 'on'
  condition:
    - condition: sun
      after: sunset
    - condition: sun
      before: sunrise
  action:
    - service: script.turn_on
      entity_id: script.evening


# ==================================================
# Aways
# ==================================================
 
- alias: 'Away'
  trigger:
    platform: state
    entity_id: input_boolean.home
    from: 'on'
    to: 'off'
  condition:
    - condition: sun
      after: sunrise
    - condition: sun
      before: sunset
  action:
    - service: script.turn_on
      entity_id: script.away
 
- alias: 'Away night'
  trigger:
    platform: state
    entity_id: input_boolean.home
    from: 'on'
    to: 'off'
  condition:
    - condition: sun
      after: sunset
    - condition: sun
      before: sunrise
  action:
    - service: script.turn_on
      entity_id: script.away_night

- alias: 'Away vacation evening'
  trigger:
    platform: sun
    event: sunset
    offset: '-00:45:00'
  condition:
    - condition: state
      entity_id: input_boolean.holidays
      state: 'on'
  action:
    - service: script.turn_on
      entity_id: script.away_vacation_evening

- alias: 'Away vacation night'
  trigger:
    platform: time
    at: '21:20:00'
  condition:
    - condition: state
      entity_id: input_boolean.holidays
      state: 'on'
  action:
    - service: script.turn_on
      entity_id: script.away_vacation_night
