- alias: 'Simon personal gmail pwnd'
  trigger:
    - platform: state
      entity_id: sensor.breaches_simoninglisgmailcom
  action:
     service: notify.notify
     data_template: 
       title: "Pwnge warning"
       message: "simon.inglis@gmail.com breach count {{ states.sensor.breaches_simoninglisgmailcom.state }}"
- alias: 'Simon 10fifteen gmail pwnd'
  trigger:
    - platform: state
      entity_id: sensor.breaches_simoninglis10fifteencomau
  action:
     service: notify.notify
     data_template: 
       title: "Pwnge warning"
       message: "simon.inglis@10fifteen.com.au breach count {{ states.sensor.breaches_simoninglis10fifteencomau.state }}"
